// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDMideJlW9ag6OFBpFoZ-JZ5i5rDVF6lo',
    appId: '1:837519824608:web:3a84a50c05dfd45abea285',
    messagingSenderId: '837519824608',
    projectId: 'car-management-347ca',
    authDomain: 'car-management-347ca.firebaseapp.com',
    storageBucket: 'car-management-347ca.appspot.com',
    measurementId: 'G-MR6SLRRTVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Rxoc-EPqvjJzEyHdXV2Y8J0YRSLEohU',
    appId: '1:837519824608:android:2e12cb4353739060bea285',
    messagingSenderId: '837519824608',
    projectId: 'car-management-347ca',
    storageBucket: 'car-management-347ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxwN6Ag97q1qlyp5m5AeZom2L4QPXCylc',
    appId: '1:837519824608:ios:b65f011a59dfe74abea285',
    messagingSenderId: '837519824608',
    projectId: 'car-management-347ca',
    storageBucket: 'car-management-347ca.appspot.com',
    androidClientId: '837519824608-2dfttgd79cqueketer94o8kok4rqard6.apps.googleusercontent.com',
    iosClientId: '837519824608-2h288kb8vbkaegh0spa0sb2lknv6kr0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxwN6Ag97q1qlyp5m5AeZom2L4QPXCylc',
    appId: '1:837519824608:ios:b65f011a59dfe74abea285',
    messagingSenderId: '837519824608',
    projectId: 'car-management-347ca',
    storageBucket: 'car-management-347ca.appspot.com',
    androidClientId: '837519824608-2dfttgd79cqueketer94o8kok4rqard6.apps.googleusercontent.com',
    iosClientId: '837519824608-2h288kb8vbkaegh0spa0sb2lknv6kr0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDMideJlW9ag6OFBpFoZ-JZ5i5rDVF6lo',
    appId: '1:837519824608:web:9328d70db09dcf57bea285',
    messagingSenderId: '837519824608',
    projectId: 'car-management-347ca',
    authDomain: 'car-management-347ca.firebaseapp.com',
    storageBucket: 'car-management-347ca.appspot.com',
    measurementId: 'G-NW6YJP9KC1',
  );

}